# Generated by Django 4.1.4 on 2023-01-21 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='buyer_reg_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=15)),
                ('District', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='category_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='f_bokking_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeapp.buyer_reg_tb')),
            ],
        ),
        migrations.CreateModel(
            name='seller_reg_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.CharField(max_length=15)),
                ('District', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='payment_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Freebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeapp.f_bokking_tb')),
            ],
        ),
        migrations.CreateModel(
            name='f_details_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('File', models.FileField(upload_to='freestuff_details')),
                ('Describtion', models.CharField(max_length=300)),
                ('Date', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Catname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeapp.category_tb')),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeapp.seller_reg_tb')),
            ],
        ),
        migrations.AddField(
            model_name='f_bokking_tb',
            name='Free_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeapp.f_details_tb'),
        ),
        migrations.AddField(
            model_name='f_bokking_tb',
            name='Seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeapp.seller_reg_tb'),
        ),
        migrations.CreateModel(
            name='exchange_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('File', models.FileField(upload_to='freestuff_details')),
                ('Describtion', models.CharField(max_length=300)),
                ('Date', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeapp.buyer_reg_tb')),
                ('Catname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeapp.category_tb')),
                ('Free_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeapp.f_details_tb')),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeapp.seller_reg_tb')),
            ],
        ),
    ]
