# Generated by Django 4.1.4 on 2023-01-21 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment_tb',
            new_name='payment_table',
        ),
    ]
