# Generated by Django 4.1.4 on 2023-01-21 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeapp', '0003_payment_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment_table',
        ),
    ]
