# Generated by Django 4.1.4 on 2023-02-11 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freeapp', '0004_delete_payment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_details_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100)),
                ('ifsecode', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('Seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeapp.seller_reg_tb')),
            ],
        ),
    ]
